import { Card, Code, Container, Grid, Link, Row, Text } from "@nextui-org/react"
import { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"

const HomePage: NextPage = () => (
  <Container>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Row
      justify="center"
      align="center"
      css={{ flex: 1, fd: "column", minHeight: "100vh", py: "$18" }}
    >
      <Text h1 css={{ textAlign: "center" }}>
        Welcome to <Link href="https://nextjs.org">Next.js!</Link>
      </Text>

      <Text size="1.5rem" css={{ textAlign: "center", my: "$18" }}>
        Get started by editing <Code>pages/index.js</Code>
      </Text>

      <Grid.Container gap={3} css={{ mw: 800 }}>
        <Grid sm={6}>
          <Card
            bordered
            clickable
            hoverable
            as="a"
            href="https://nextjs.org/docs"
            css={{ px: "$2", py: "$6" }}
          >
            <Text h2 css={{ mb: "$8" }}>
              Documentation &rarr;
            </Text>
            <Text size="1.25rem">
              Find in-depth information about Next.js features and API.
            </Text>
          </Card>
        </Grid>

        <Grid sm={6}>
          <Card
            bordered
            clickable
            hoverable
            as="a"
            href="https://nextjs.org/learn"
            css={{ px: "$2", py: "$6" }}
          >
            <Text h2 css={{ mb: "$8" }}>
              Learn &rarr;
            </Text>
            <Text size="1.25rem">
              Learn about Next.js in an interactive course with quizzes!
            </Text>
          </Card>
        </Grid>

        <Grid sm={6}>
          <Card
            bordered
            clickable
            hoverable
            as="a"
            href="https://github.com/vercel/next.js/tree/canary/examples"
            css={{ px: "$2", py: "$6" }}
          >
            <Text h2 css={{ mb: "$8" }}>
              Examples &rarr;
            </Text>
            <Text size="1.25rem">
              Discover and deploy boilerplate example Next.js projects.
            </Text>
          </Card>
        </Grid>

        <Grid sm={6}>
          <Card
            bordered
            clickable
            hoverable
            as="a"
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            css={{ px: "$2", py: "$6" }}
          >
            <Text h2 css={{ mb: "$8" }}>
              Deploy &rarr;
            </Text>
            <Text size="1.25rem">
              Instantly deploy your Next.js site to a public URL with Vercel.
            </Text>
          </Card>
        </Grid>
      </Grid.Container>
    </Row>

    <Row
      justify="center"
      align="center"
      css={{
        py: "$12",
        borderTop: "1px solid $border",
      }}
    >
      <Link
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
        css={{ d: "flex", jc: "center", ai: "center", fg: 1 }}
      >
        Powered by{" "}
        <Text as="span" css={{ h: "1em", ml: "$4" }}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </Text>
      </Link>
    </Row>
  </Container>
)

export default HomePage
